const mongoose = require('mongoose');

const BookingSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true, index: true },
  bookingId: { type: String, unique: true, sparse: true, index: true },
  studentId: { type: String, required: true, index: true },
  studentName: { type: String, default: '' },
  interviewerId: { type: String, required: true, index: true },
  interviewerName: { type: String, default: '' },
  domain: { type: String, default: '' },
  preferredSlots: { type: Array, default: [] },
  selectedSlot: { type: Object, default: null },
  selectedDate: { type: String, default: '' },
  slotLabel: { type: String, default: '' },
  slotStartTime: { type: String, default: '' },
  slotEndTime: { type: String, default: '' },
  timezone: { type: String, default: 'Asia/Kolkata' },
  approvalStatus: { type: String, default: 'pending' },
  approvedAt: { type: String, default: '' },
  approvedDate: { type: String, default: '' },
  approvedTime: { type: String, default: '' },
  bookingStatus: { type: String, default: 'pending' },
  confirmedAt: { type: String, default: '' },
  confirmedDate: { type: String, default: '' },
  confirmedTime: { type: String, default: '' },
  conflictChecks: { type: Object, default: {} },
  bookingEvents: { type: Array, default: [] },
  date: { type: String, default: '' },
  slot: { type: String, default: '' },
  status: {
    type: String,
    default: 'pending',
    enum: ['pending', 'accepted', 'confirmed', 'rejected', 'reschedule_requested', 'reschedule_slot_selected', 'cancelled', 'cancelled_by_interviewer', 'cancelled_by_student', 'no_response', 'meeting_link_uploaded', 'session_ended', 'completed', 'reassigned', 'expired', 'pending_payment', 'pending_verification', 'refund_requested', 'refund_required', 'refund_proof_submitted', 'refund_disputed', 'refund_completed']
  },
  paymentProof: { type: String, default: null },
  paymentProofName: { type: String, default: '' },
  paymentStatus: { type: String, enum: ['not_uploaded', 'pending_verification', 'screenshot_uploaded', 'verified', 'rejected'], default: 'not_uploaded' },
  paymentAmount: { type: Number, default: 50 },
  paymentCurrency: { type: String, default: 'INR' },
  paymentVerifiedAt: { type: String, default: null },
  paymentVerifiedBy: { type: String, default: null },
  paymentApprovedByName: { type: String, default: '' },
  paymentRejectedAt: { type: String, default: '' },
  paymentRejectedByName: { type: String, default: '' },
  paymentRejectionReason: { type: String, default: '' },
  paymentUtr: { type: String, default: '' },
  paymentSubmissions: { type: Array, default: [] },
  utiNumber: { type: String, default: '' },
  meetingLink: { type: String, default: null },
  meetingLinkUploadedAt: { type: String, default: null },
  studentJoinedAt: { type: String, default: null },
  sessionEndedAt: { type: String, default: null },
  zoomLink: { type: String, default: '' },
  approvalDeadlineAt: { type: String, default: null },
  interviewerMessage: { type: String, default: '' },
  rescheduleProposal: { type: Object, default: null },
  refundStatus: { type: String, enum: ['', 'required', 'proof_submitted', 'disputed', 'completed', 'admin_review_required'], default: '' },
  refundAmount: { type: Number, default: 0 },
  refundCurrency: { type: String, default: 'INR' },
  refundSnapshot: { type: Object, default: null },
  refundRequiredAt: { type: String, default: '' },
  refundRequestedAt: { type: String, default: '' },
  refundCancellationDate: { type: String, default: '' },
  refundCancellationTime: { type: String, default: '' },
  refundPendingTriggeredAt: { type: String, default: '' },
  refundOverdueTriggeredAt: { type: String, default: '' },
  refundAdminReviewRequiredAt: { type: String, default: '' },
  refundAdminReviewIssueId: { type: String, default: '' },
  refundUtr: { type: String, default: '' },
  refundSubmittedAt: { type: String, default: '' },
  refundSubmittedDate: { type: String, default: '' },
  refundSubmittedTime: { type: String, default: '' },
  refundSubmission: { type: Object, default: null },
  refundEvents: { type: Array, default: [] },
  refundProof: {
    fileName: String,
    filePath: String,
    mimeType: String,
    uploadedAt: String
  },
  refundCompletedAt: { type: String, default: '' },
  refundConfirmedAt: { type: String, default: '' },
  refundDisputedAt: { type: String, default: '' },
  refundDisputeId: { type: String, default: '' },
  hangingTagState: { type: Object, default: null },
  tagNotificationSentAt: { type: Object, default: {} },
  qualityCheck: { type: Object, default: null },
  notifications: { type: Array, default: [] },
  feedback: { type: Object, default: null },
  feedbackViewedAt: { type: String, default: '' },
  feedbackReminderSentAt: { type: String, default: '' },
  feedbackDashboardReminderAt: { type: String, default: '' },
  studentFeedback: { type: Object, default: null },
  createdAt: { type: String, default: () => new Date().toISOString() },
  updatedAt: { type: String, default: () => new Date().toISOString() }
}, { versionKey: false });

module.exports = mongoose.models.Booking || mongoose.model('Booking', BookingSchema);
